/**
 * Application-wide constants.
 */

export const UPLOAD_STATUS = {
  PENDING: 'PENDING',
  UPLOADING: 'UPLOADING',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED'
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
} as const;

export const ERROR_CODES = {
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  INVALID_CHUNK_INDEX: 'INVALID_CHUNK_INDEX',
  MISSING_CHUNKS: 'MISSING_CHUNKS',
  CHUNK_SIZE_MISMATCH: 'CHUNK_SIZE_MISMATCH',
  DATABASE_ERROR: 'DATABASE_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;

export const HEADER_REQUEST_ID = 'x-request-id';
export const HEADER_UPLOAD_ID = 'x-upload-id';
